#!/bin/sh /etc/rc.common

START=20
USE_PROCD=1

start_service() {
    # Baca nilai dari /etc/config/jsholat
    local service_status=$(uci get jsholat.setting.service 2>/dev/null)
    echo "Service status: $service_status" > /dev/console  # Log ke console

    # Jalankan service hanya jika status On (1)
    if [ "$service_status" = "1" ]; then
        echo "Starting jsholat service..." > /dev/console  # Log ke console
        procd_open_instance
        procd_set_param command /usr/bin/jsholat
        procd_set_param respawn 300 5 10  # Respawn jika service mati
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
    else
        echo "Service is disabled. Not starting jsholat." > /dev/console  # Log ke console
    fi
}

stop_service() {
    # Dapatkan PID dari proses jsholat
    local pid=$(pgrep -f "/usr/bin/jsholat")
    echo "Stopping jsholat service (PID: $pid)..." > /dev/console  # Log ke console

    # Hentikan service jika PID ditemukan
    if [ -n "$pid" ]; then
        kill "$pid"
    fi
}

reload_service() {
    # Reload service (jika diperlukan)
    stop_service
    start_service
}